# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f9f52cb4d7eb1c3d2dd676340a0568181ae1dabe9cdceab6cb90c17f86145eb0b66e7c1593a774bbbc840b24c8e93b05b08548dadac4ecb9eef070c575db16c

test:
  secret_key_base: 3d03fce672673a983c182c3c0979e3869cc7c83d8eeec9fce2587f8431f743fd0fe1a2128176dcb5e739422e0da6cbb09bc8e40d69a2c43bd1b40d93bf7c3c0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
